#  Data Wrangling

## importing Dataset

In [107]:
import os
downloads_path=os.path.join(os.path.expanduser("~"),"Downloads")
print(downloads_path)

C:\Users\ramya\Downloads

In [4]:
import pandas as pd
import numpy as np

netflix = pd.read_csv(
    r"C:\Users\ramya\Downloads\netflix_titles.csv\netflix_titles.csv",
    sep=";",
    encoding="latin-1",
    engine="python",
    on_bad_lines="skip"
)
netflix.head()

  show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
0  s1,Movie,Dick Johnson Is Dead,Kirsten Johnson,...
1  s2,TV Show,Blood & Water,,"Ama Qamata, Khosi N...
2  s3,TV Show,Ganglands,Julien Leclercq,"Sami Bou...
3  s4,TV Show,Jailbirds New Orleans,,,,"September...
4  s5,TV Show,Kota Factory,,"Mayur More, Jitendra...

# 1.Perform merge, join, concatenate, combine and reshape in the context of data wrangling.

## 1.1  Merge

## Simple merge on a key

In [5]:
import pandas as pd

# Load your dataset
df = pd.read_csv(r"C:\Users\ramya\Downloads\netflix_titles.csv\netflix_titles.csv")

# Inspect first few rows
print(df.head())

  show_id     type                  title         director  \
0      s1    Movie   Dick Johnson Is Dead  Kirsten Johnson
1      s2  TV Show          Blood & Water              NaN
2      s3  TV Show              Ganglands  Julien Leclercq
3      s4  TV Show  Jailbirds New Orleans              NaN
4      s5  TV Show           Kota Factory              NaN

                                                cast        country  \
0                                                NaN  United States
1  Ama Qamata, Khosi Ngema, Gail Mabalane, Thaban...   South Africa
2  Sami Bouajila, Tracy Gotoas, Samuel Jouy, Nabi...            NaN
3                                                NaN            NaN
4  Mayur More, Jitendra Kumar, Ranjan Raj, Alam K...          India

           date_added  release_year rating   duration  \
0  September 25, 2021          2020  PG-13     90 min
1  September 24, 2021          2021  TV-MA  2 Seasons
2  September 24, 2021          2021  TV-MA   1 Season
3  September 24, 2021          2021  TV-MA   1 Season
4  September 24, 2021          2021  TV-MA  2 Seasons

                                           listed_in  \
0                                      Documentaries
1    International TV Shows, TV Dramas, TV Mysteries
2  Crime TV Shows, International TV Shows, TV Act...
3                             Docuseries, Reality TV
4  International TV Shows, Romantic TV Shows, TV ...

                                         description
0  As her father nears the end of his life, filmm...
1  After crossing paths at a party, a Cape Town t...
2  To protect his family from a powerful drug lor...
3  Feuds, flirtations and toilet talk go down amo...
4  In a city of coaching centers known to train I...

In [6]:
netflix.columns

Index(['show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description'], dtype='str')

In [7]:
print(type(df.columns))

<class 'pandas.Index'>

In [8]:
print("Running clean test...")

df.columns = df.columns.astype(str)
df.columns = df.columns.str.strip()
df.columns = df.columns.str.lower()

print(df.columns)

Running clean test...
Index(['show_id', 'type', 'title', 'director', 'cast', 'country', 'date_added',
       'release_year', 'rating', 'duration', 'listed_in', 'description'],
      dtype='str')

In [9]:
df.columns = df.columns.astype(str)
df.columns = df.columns.str.strip()
df.columns = df.columns.str.replace(';', '')   # 👈 IMPORTANT
df.columns = df.columns.str.lower()

In [10]:
print(df.columns)

Index(['show_id', 'type', 'title', 'director', 'cast', 'country', 'date_added',
       'release_year', 'rating', 'duration', 'listed_in', 'description'],
      dtype='str')

In [11]:
import pandas as pd
merged=pd.merge(df,df,on="title")

### Simple merge on show_id

In [12]:
merged = pd.merge(df, df, on="show_id")
print(merged.head())

  show_id   type_x                title_x       director_x  \
0      s1    Movie   Dick Johnson Is Dead  Kirsten Johnson
1      s2  TV Show          Blood & Water              NaN
2      s3  TV Show              Ganglands  Julien Leclercq
3      s4  TV Show  Jailbirds New Orleans              NaN
4      s5  TV Show           Kota Factory              NaN

                                              cast_x      country_x  \
0                                                NaN  United States
1  Ama Qamata, Khosi Ngema, Gail Mabalane, Thaban...   South Africa
2  Sami Bouajila, Tracy Gotoas, Samuel Jouy, Nabi...            NaN
3                                                NaN            NaN
4  Mayur More, Jitendra Kumar, Ranjan Raj, Alam K...          India

         date_added_x  release_year_x rating_x duration_x  ...  \
0  September 25, 2021            2020    PG-13     90 min  ...
1  September 24, 2021            2021    TV-MA  2 Seasons  ...
2  September 24, 2021            2021    TV-MA   1 Season  ...
3  September 24, 2021            2021    TV-MA   1 Season  ...
4  September 24, 2021            2021    TV-MA  2 Seasons  ...

                 title_y       director_y  \
0   Dick Johnson Is Dead  Kirsten Johnson
1          Blood & Water              NaN
2              Ganglands  Julien Leclercq
3  Jailbirds New Orleans              NaN
4           Kota Factory              NaN

                                              cast_y      country_y  \
0                                                NaN  United States
1  Ama Qamata, Khosi Ngema, Gail Mabalane, Thaban...   South Africa
2  Sami Bouajila, Tracy Gotoas, Samuel Jouy, Nabi...            NaN
3                                                NaN            NaN
4  Mayur More, Jitendra Kumar, Ranjan Raj, Alam K...          India

         date_added_y release_year_y rating_y duration_y  \
0  September 25, 2021           2020    PG-13     90 min
1  September 24, 2021           2021    TV-MA  2 Seasons
2  September 24, 2021           2021    TV-MA   1 Season
3  September 24, 2021           2021    TV-MA   1 Season
4  September 24, 2021           2021    TV-MA  2 Seasons

                                         listed_in_y  \
0                                      Documentaries
1    International TV Shows, TV Dramas, TV Mysteries
2  Crime TV Shows, International TV Shows, TV Act...
3                             Docuseries, Reality TV
4  International TV Shows, Romantic TV Shows, TV ...

                                       description_y
0  As her father nears the end of his life, filmm...
1  After crossing paths at a party, a Cape Town t...
2  To protect his family from a powerful drug lor...
3  Feuds, flirtations and toilet talk go down amo...
4  In a city of coaching centers known to train I...

[5 rows x 23 columns]

###  Inner merge

In [13]:
merged = pd.merge(df, df, on="show_id", how="inner")
print(merged.head())

  show_id   type_x                title_x       director_x  \
0      s1    Movie   Dick Johnson Is Dead  Kirsten Johnson
1      s2  TV Show          Blood & Water              NaN
2      s3  TV Show              Ganglands  Julien Leclercq
3      s4  TV Show  Jailbirds New Orleans              NaN
4      s5  TV Show           Kota Factory              NaN

                                              cast_x      country_x  \
0                                                NaN  United States
1  Ama Qamata, Khosi Ngema, Gail Mabalane, Thaban...   South Africa
2  Sami Bouajila, Tracy Gotoas, Samuel Jouy, Nabi...            NaN
3                                                NaN            NaN
4  Mayur More, Jitendra Kumar, Ranjan Raj, Alam K...          India

         date_added_x  release_year_x rating_x duration_x  ...  \
0  September 25, 2021            2020    PG-13     90 min  ...
1  September 24, 2021            2021    TV-MA  2 Seasons  ...
2  September 24, 2021            2021    TV-MA   1 Season  ...
3  September 24, 2021            2021    TV-MA   1 Season  ...
4  September 24, 2021            2021    TV-MA  2 Seasons  ...

                 title_y       director_y  \
0   Dick Johnson Is Dead  Kirsten Johnson
1          Blood & Water              NaN
2              Ganglands  Julien Leclercq
3  Jailbirds New Orleans              NaN
4           Kota Factory              NaN

                                              cast_y      country_y  \
0                                                NaN  United States
1  Ama Qamata, Khosi Ngema, Gail Mabalane, Thaban...   South Africa
2  Sami Bouajila, Tracy Gotoas, Samuel Jouy, Nabi...            NaN
3                                                NaN            NaN
4  Mayur More, Jitendra Kumar, Ranjan Raj, Alam K...          India

         date_added_y release_year_y rating_y duration_y  \
0  September 25, 2021           2020    PG-13     90 min
1  September 24, 2021           2021    TV-MA  2 Seasons
2  September 24, 2021           2021    TV-MA   1 Season
3  September 24, 2021           2021    TV-MA   1 Season
4  September 24, 2021           2021    TV-MA  2 Seasons

                                         listed_in_y  \
0                                      Documentaries
1    International TV Shows, TV Dramas, TV Mysteries
2  Crime TV Shows, International TV Shows, TV Act...
3                             Docuseries, Reality TV
4  International TV Shows, Romantic TV Shows, TV ...

                                       description_y
0  As her father nears the end of his life, filmm...
1  After crossing paths at a party, a Cape Town t...
2  To protect his family from a powerful drug lor...
3  Feuds, flirtations and toilet talk go down amo...
4  In a city of coaching centers known to train I...

[5 rows x 23 columns]

###  Left merge

In [14]:
merged = pd.merge(df, df, on="show_id", how="left")
print(merged.head())

  show_id   type_x                title_x       director_x  \
0      s1    Movie   Dick Johnson Is Dead  Kirsten Johnson
1      s2  TV Show          Blood & Water              NaN
2      s3  TV Show              Ganglands  Julien Leclercq
3      s4  TV Show  Jailbirds New Orleans              NaN
4      s5  TV Show           Kota Factory              NaN

                                              cast_x      country_x  \
0                                                NaN  United States
1  Ama Qamata, Khosi Ngema, Gail Mabalane, Thaban...   South Africa
2  Sami Bouajila, Tracy Gotoas, Samuel Jouy, Nabi...            NaN
3                                                NaN            NaN
4  Mayur More, Jitendra Kumar, Ranjan Raj, Alam K...          India

         date_added_x  release_year_x rating_x duration_x  ...  \
0  September 25, 2021            2020    PG-13     90 min  ...
1  September 24, 2021            2021    TV-MA  2 Seasons  ...
2  September 24, 2021            2021    TV-MA   1 Season  ...
3  September 24, 2021            2021    TV-MA   1 Season  ...
4  September 24, 2021            2021    TV-MA  2 Seasons  ...

                 title_y       director_y  \
0   Dick Johnson Is Dead  Kirsten Johnson
1          Blood & Water              NaN
2              Ganglands  Julien Leclercq
3  Jailbirds New Orleans              NaN
4           Kota Factory              NaN

                                              cast_y      country_y  \
0                                                NaN  United States
1  Ama Qamata, Khosi Ngema, Gail Mabalane, Thaban...   South Africa
2  Sami Bouajila, Tracy Gotoas, Samuel Jouy, Nabi...            NaN
3                                                NaN            NaN
4  Mayur More, Jitendra Kumar, Ranjan Raj, Alam K...          India

         date_added_y release_year_y rating_y duration_y  \
0  September 25, 2021           2020    PG-13     90 min
1  September 24, 2021           2021    TV-MA  2 Seasons
2  September 24, 2021           2021    TV-MA   1 Season
3  September 24, 2021           2021    TV-MA   1 Season
4  September 24, 2021           2021    TV-MA  2 Seasons

                                         listed_in_y  \
0                                      Documentaries
1    International TV Shows, TV Dramas, TV Mysteries
2  Crime TV Shows, International TV Shows, TV Act...
3                             Docuseries, Reality TV
4  International TV Shows, Romantic TV Shows, TV ...

                                       description_y
0  As her father nears the end of his life, filmm...
1  After crossing paths at a party, a Cape Town t...
2  To protect his family from a powerful drug lor...
3  Feuds, flirtations and toilet talk go down amo...
4  In a city of coaching centers known to train I...

[5 rows x 23 columns]

### Right merge

In [15]:
merged = pd.merge(df, df, on="show_id", how="right")
print(merged.head())

  show_id   type_x                title_x       director_x  \
0      s1    Movie   Dick Johnson Is Dead  Kirsten Johnson
1      s2  TV Show          Blood & Water              NaN
2      s3  TV Show              Ganglands  Julien Leclercq
3      s4  TV Show  Jailbirds New Orleans              NaN
4      s5  TV Show           Kota Factory              NaN

                                              cast_x      country_x  \
0                                                NaN  United States
1  Ama Qamata, Khosi Ngema, Gail Mabalane, Thaban...   South Africa
2  Sami Bouajila, Tracy Gotoas, Samuel Jouy, Nabi...            NaN
3                                                NaN            NaN
4  Mayur More, Jitendra Kumar, Ranjan Raj, Alam K...          India

         date_added_x  release_year_x rating_x duration_x  ...  \
0  September 25, 2021            2020    PG-13     90 min  ...
1  September 24, 2021            2021    TV-MA  2 Seasons  ...
2  September 24, 2021            2021    TV-MA   1 Season  ...
3  September 24, 2021            2021    TV-MA   1 Season  ...
4  September 24, 2021            2021    TV-MA  2 Seasons  ...

                 title_y       director_y  \
0   Dick Johnson Is Dead  Kirsten Johnson
1          Blood & Water              NaN
2              Ganglands  Julien Leclercq
3  Jailbirds New Orleans              NaN
4           Kota Factory              NaN

                                              cast_y      country_y  \
0                                                NaN  United States
1  Ama Qamata, Khosi Ngema, Gail Mabalane, Thaban...   South Africa
2  Sami Bouajila, Tracy Gotoas, Samuel Jouy, Nabi...            NaN
3                                                NaN            NaN
4  Mayur More, Jitendra Kumar, Ranjan Raj, Alam K...          India

         date_added_y release_year_y rating_y duration_y  \
0  September 25, 2021           2020    PG-13     90 min
1  September 24, 2021           2021    TV-MA  2 Seasons
2  September 24, 2021           2021    TV-MA   1 Season
3  September 24, 2021           2021    TV-MA   1 Season
4  September 24, 2021           2021    TV-MA  2 Seasons

                                         listed_in_y  \
0                                      Documentaries
1    International TV Shows, TV Dramas, TV Mysteries
2  Crime TV Shows, International TV Shows, TV Act...
3                             Docuseries, Reality TV
4  International TV Shows, Romantic TV Shows, TV ...

                                       description_y
0  As her father nears the end of his life, filmm...
1  After crossing paths at a party, a Cape Town t...
2  To protect his family from a powerful drug lor...
3  Feuds, flirtations and toilet talk go down amo...
4  In a city of coaching centers known to train I...

[5 rows x 23 columns]

### Outer merge

In [16]:
merged = pd.merge(df, df, on="show_id", how="outer")
print(merged.head())

  show_id   type_x               title_x       director_x  \
0      s1    Movie  Dick Johnson Is Dead  Kirsten Johnson
1     s10    Movie          The Starling   Theodore Melfi
2    s100  TV Show          On the Verge              NaN
3   s1000    Movie              Stowaway        Joe Penna
4   s1001    Movie              Wild Dog  Ahishor Solomon

                                              cast_x               country_x  \
0                                                NaN           United States
1  Melissa McCarthy, Chris O'Dowd, Kevin Kline, T...           United States
2  Julie Delpy, Elisabeth Shue, Sarah Jones, Alex...   France, United States
3  Anna Kendrick, Toni Collette, Daniel Dae Kim, ...  Germany, United States
4  Nagarjuna Akkineni, Dia Mirza, Saiyami Kher, A...                     NaN

         date_added_x  release_year_x rating_x duration_x  ...  \
0  September 25, 2021            2020    PG-13     90 min  ...
1  September 24, 2021            2021    PG-13    104 min  ...
2   September 7, 2021            2021    TV-MA   1 Season  ...
3      April 22, 2021            2021    TV-MA    116 min  ...
4      April 22, 2021            2020    TV-MA    126 min  ...

                title_y       director_y  \
0  Dick Johnson Is Dead  Kirsten Johnson
1          The Starling   Theodore Melfi
2          On the Verge              NaN
3              Stowaway        Joe Penna
4              Wild Dog  Ahishor Solomon

                                              cast_y               country_y  \
0                                                NaN           United States
1  Melissa McCarthy, Chris O'Dowd, Kevin Kline, T...           United States
2  Julie Delpy, Elisabeth Shue, Sarah Jones, Alex...   France, United States
3  Anna Kendrick, Toni Collette, Daniel Dae Kim, ...  Germany, United States
4  Nagarjuna Akkineni, Dia Mirza, Saiyami Kher, A...                     NaN

         date_added_y release_year_y rating_y duration_y  \
0  September 25, 2021           2020    PG-13     90 min
1  September 24, 2021           2021    PG-13    104 min
2   September 7, 2021           2021    TV-MA   1 Season
3      April 22, 2021           2021    TV-MA    116 min
4      April 22, 2021           2020    TV-MA    126 min

                                listed_in_y  \
0                             Documentaries
1                          Comedies, Dramas
2                    TV Comedies, TV Dramas
3   Dramas, International Movies, Thrillers
4  Action & Adventure, International Movies

                                       description_y
0  As her father nears the end of his life, filmm...
1  A woman adjusting to life after a loss contend...
2  Four women — a chef, a single mom, an heiress ...
3  A three-person crew on a mission to Mars faces...
4  A brash but brilliant Indian intelligence agen...

[5 rows x 23 columns]

### Merge with suffixes

In [17]:
merged = pd.merge(df, df, on="show_id", suffixes=("_A","_B"))
print(merged.head())

  show_id   type_A                title_A       director_A  \
0      s1    Movie   Dick Johnson Is Dead  Kirsten Johnson
1      s2  TV Show          Blood & Water              NaN
2      s3  TV Show              Ganglands  Julien Leclercq
3      s4  TV Show  Jailbirds New Orleans              NaN
4      s5  TV Show           Kota Factory              NaN

                                              cast_A      country_A  \
0                                                NaN  United States
1  Ama Qamata, Khosi Ngema, Gail Mabalane, Thaban...   South Africa
2  Sami Bouajila, Tracy Gotoas, Samuel Jouy, Nabi...            NaN
3                                                NaN            NaN
4  Mayur More, Jitendra Kumar, Ranjan Raj, Alam K...          India

         date_added_A  release_year_A rating_A duration_A  ...  \
0  September 25, 2021            2020    PG-13     90 min  ...
1  September 24, 2021            2021    TV-MA  2 Seasons  ...
2  September 24, 2021            2021    TV-MA   1 Season  ...
3  September 24, 2021            2021    TV-MA   1 Season  ...
4  September 24, 2021            2021    TV-MA  2 Seasons  ...

                 title_B       director_B  \
0   Dick Johnson Is Dead  Kirsten Johnson
1          Blood & Water              NaN
2              Ganglands  Julien Leclercq
3  Jailbirds New Orleans              NaN
4           Kota Factory              NaN

                                              cast_B      country_B  \
0                                                NaN  United States
1  Ama Qamata, Khosi Ngema, Gail Mabalane, Thaban...   South Africa
2  Sami Bouajila, Tracy Gotoas, Samuel Jouy, Nabi...            NaN
3                                                NaN            NaN
4  Mayur More, Jitendra Kumar, Ranjan Raj, Alam K...          India

         date_added_B release_year_B rating_B duration_B  \
0  September 25, 2021           2020    PG-13     90 min
1  September 24, 2021           2021    TV-MA  2 Seasons
2  September 24, 2021           2021    TV-MA   1 Season
3  September 24, 2021           2021    TV-MA   1 Season
4  September 24, 2021           2021    TV-MA  2 Seasons

                                         listed_in_B  \
0                                      Documentaries
1    International TV Shows, TV Dramas, TV Mysteries
2  Crime TV Shows, International TV Shows, TV Act...
3                             Docuseries, Reality TV
4  International TV Shows, Romantic TV Shows, TV ...

                                       description_B
0  As her father nears the end of his life, filmm...
1  After crossing paths at a party, a Cape Town t...
2  To protect his family from a powerful drug lor...
3  Feuds, flirtations and toilet talk go down amo...
4  In a city of coaching centers known to train I...

[5 rows x 23 columns]

### Merge on multiple keys

In [18]:
merged = pd.merge(df, df, on=["show_id","type"])
print(merged.head())

  show_id     type                title_x       director_x  \
0      s1    Movie   Dick Johnson Is Dead  Kirsten Johnson
1      s2  TV Show          Blood & Water              NaN
2      s3  TV Show              Ganglands  Julien Leclercq
3      s4  TV Show  Jailbirds New Orleans              NaN
4      s5  TV Show           Kota Factory              NaN

                                              cast_x      country_x  \
0                                                NaN  United States
1  Ama Qamata, Khosi Ngema, Gail Mabalane, Thaban...   South Africa
2  Sami Bouajila, Tracy Gotoas, Samuel Jouy, Nabi...            NaN
3                                                NaN            NaN
4  Mayur More, Jitendra Kumar, Ranjan Raj, Alam K...          India

         date_added_x  release_year_x rating_x duration_x  ...  \
0  September 25, 2021            2020    PG-13     90 min  ...
1  September 24, 2021            2021    TV-MA  2 Seasons  ...
2  September 24, 2021            2021    TV-MA   1 Season  ...
3  September 24, 2021            2021    TV-MA   1 Season  ...
4  September 24, 2021            2021    TV-MA  2 Seasons  ...

                 title_y       director_y  \
0   Dick Johnson Is Dead  Kirsten Johnson
1          Blood & Water              NaN
2              Ganglands  Julien Leclercq
3  Jailbirds New Orleans              NaN
4           Kota Factory              NaN

                                              cast_y      country_y  \
0                                                NaN  United States
1  Ama Qamata, Khosi Ngema, Gail Mabalane, Thaban...   South Africa
2  Sami Bouajila, Tracy Gotoas, Samuel Jouy, Nabi...            NaN
3                                                NaN            NaN
4  Mayur More, Jitendra Kumar, Ranjan Raj, Alam K...          India

         date_added_y release_year_y rating_y  duration_y  \
0  September 25, 2021           2020    PG-13      90 min
1  September 24, 2021           2021    TV-MA   2 Seasons
2  September 24, 2021           2021    TV-MA    1 Season
3  September 24, 2021           2021    TV-MA    1 Season
4  September 24, 2021           2021    TV-MA   2 Seasons

                                         listed_in_y  \
0                                      Documentaries
1    International TV Shows, TV Dramas, TV Mysteries
2  Crime TV Shows, International TV Shows, TV Act...
3                             Docuseries, Reality TV
4  International TV Shows, Romantic TV Shows, TV ...

                                       description_y
0  As her father nears the end of his life, filmm...
1  After crossing paths at a party, a Cape Town t...
2  To protect his family from a powerful drug lor...
3  Feuds, flirtations and toilet talk go down amo...
4  In a city of coaching centers known to train I...

[5 rows x 22 columns]

### Merge with indicator

In [19]:
merged = pd.merge(df, df, on="show_id", how="outer", indicator=True)
print(merged.head())

  show_id   type_x               title_x       director_x  \
0      s1    Movie  Dick Johnson Is Dead  Kirsten Johnson
1     s10    Movie          The Starling   Theodore Melfi
2    s100  TV Show          On the Verge              NaN
3   s1000    Movie              Stowaway        Joe Penna
4   s1001    Movie              Wild Dog  Ahishor Solomon

                                              cast_x               country_x  \
0                                                NaN           United States
1  Melissa McCarthy, Chris O'Dowd, Kevin Kline, T...           United States
2  Julie Delpy, Elisabeth Shue, Sarah Jones, Alex...   France, United States
3  Anna Kendrick, Toni Collette, Daniel Dae Kim, ...  Germany, United States
4  Nagarjuna Akkineni, Dia Mirza, Saiyami Kher, A...                     NaN

         date_added_x  release_year_x rating_x duration_x  ...  \
0  September 25, 2021            2020    PG-13     90 min  ...
1  September 24, 2021            2021    PG-13    104 min  ...
2   September 7, 2021            2021    TV-MA   1 Season  ...
3      April 22, 2021            2021    TV-MA    116 min  ...
4      April 22, 2021            2020    TV-MA    126 min  ...

        director_y                                             cast_y  \
0  Kirsten Johnson                                                NaN
1   Theodore Melfi  Melissa McCarthy, Chris O'Dowd, Kevin Kline, T...
2              NaN  Julie Delpy, Elisabeth Shue, Sarah Jones, Alex...
3        Joe Penna  Anna Kendrick, Toni Collette, Daniel Dae Kim, ...
4  Ahishor Solomon  Nagarjuna Akkineni, Dia Mirza, Saiyami Kher, A...

                country_y        date_added_y release_year_y rating_y  \
0           United States  September 25, 2021           2020    PG-13
1           United States  September 24, 2021           2021    PG-13
2   France, United States   September 7, 2021           2021    TV-MA
3  Germany, United States      April 22, 2021           2021    TV-MA
4                     NaN      April 22, 2021           2020    TV-MA

  duration_y                               listed_in_y  \
0     90 min                             Documentaries
1    104 min                          Comedies, Dramas
2   1 Season                    TV Comedies, TV Dramas
3    116 min   Dramas, International Movies, Thrillers
4    126 min  Action & Adventure, International Movies

                                       description_y _merge
0  As her father nears the end of his life, filmm...   both
1  A woman adjusting to life after a loss contend...   both
2  Four women — a chef, a single mom, an heiress ...   both
3  A three-person crew on a mission to Mars faces...   both
4  A brash but brilliant Indian intelligence agen...   both

[5 rows x 24 columns]

### Merge with validate

In [20]:
merged = pd.merge(df, df, on="show_id", validate="one_to_one")
print(merged.head())

  show_id   type_x                title_x       director_x  \
0      s1    Movie   Dick Johnson Is Dead  Kirsten Johnson
1      s2  TV Show          Blood & Water              NaN
2      s3  TV Show              Ganglands  Julien Leclercq
3      s4  TV Show  Jailbirds New Orleans              NaN
4      s5  TV Show           Kota Factory              NaN

                                              cast_x      country_x  \
0                                                NaN  United States
1  Ama Qamata, Khosi Ngema, Gail Mabalane, Thaban...   South Africa
2  Sami Bouajila, Tracy Gotoas, Samuel Jouy, Nabi...            NaN
3                                                NaN            NaN
4  Mayur More, Jitendra Kumar, Ranjan Raj, Alam K...          India

         date_added_x  release_year_x rating_x duration_x  ...  \
0  September 25, 2021            2020    PG-13     90 min  ...
1  September 24, 2021            2021    TV-MA  2 Seasons  ...
2  September 24, 2021            2021    TV-MA   1 Season  ...
3  September 24, 2021            2021    TV-MA   1 Season  ...
4  September 24, 2021            2021    TV-MA  2 Seasons  ...

                 title_y       director_y  \
0   Dick Johnson Is Dead  Kirsten Johnson
1          Blood & Water              NaN
2              Ganglands  Julien Leclercq
3  Jailbirds New Orleans              NaN
4           Kota Factory              NaN

                                              cast_y      country_y  \
0                                                NaN  United States
1  Ama Qamata, Khosi Ngema, Gail Mabalane, Thaban...   South Africa
2  Sami Bouajila, Tracy Gotoas, Samuel Jouy, Nabi...            NaN
3                                                NaN            NaN
4  Mayur More, Jitendra Kumar, Ranjan Raj, Alam K...          India

         date_added_y release_year_y rating_y duration_y  \
0  September 25, 2021           2020    PG-13     90 min
1  September 24, 2021           2021    TV-MA  2 Seasons
2  September 24, 2021           2021    TV-MA   1 Season
3  September 24, 2021           2021    TV-MA   1 Season
4  September 24, 2021           2021    TV-MA  2 Seasons

                                         listed_in_y  \
0                                      Documentaries
1    International TV Shows, TV Dramas, TV Mysteries
2  Crime TV Shows, International TV Shows, TV Act...
3                             Docuseries, Reality TV
4  International TV Shows, Romantic TV Shows, TV ...

                                       description_y
0  As her father nears the end of his life, filmm...
1  After crossing paths at a party, a Cape Town t...
2  To protect his family from a powerful drug lor...
3  Feuds, flirtations and toilet talk go down amo...
4  In a city of coaching centers known to train I...

[5 rows x 23 columns]

###  Merge selected columns

In [21]:
df1 = df[["show_id","title","release_year"]]
df2 = df[["show_id","director","country"]]
merged = pd.merge(df1, df2, on="show_id")
print(merged.head())

  show_id                  title  release_year         director        country
0      s1   Dick Johnson Is Dead          2020  Kirsten Johnson  United States
1      s2          Blood & Water          2021              NaN   South Africa
2      s3              Ganglands          2021  Julien Leclercq            NaN
3      s4  Jailbirds New Orleans          2021              NaN            NaN
4      s5           Kota Factory          2021              NaN          India

### Merge with index

In [22]:
merged = pd.merge(df, df, left_index=True, right_index=True)
print(merged.head())

  show_id_x   type_x                title_x       director_x  \
0        s1    Movie   Dick Johnson Is Dead  Kirsten Johnson
1        s2  TV Show          Blood & Water              NaN
2        s3  TV Show              Ganglands  Julien Leclercq
3        s4  TV Show  Jailbirds New Orleans              NaN
4        s5  TV Show           Kota Factory              NaN

                                              cast_x      country_x  \
0                                                NaN  United States
1  Ama Qamata, Khosi Ngema, Gail Mabalane, Thaban...   South Africa
2  Sami Bouajila, Tracy Gotoas, Samuel Jouy, Nabi...            NaN
3                                                NaN            NaN
4  Mayur More, Jitendra Kumar, Ranjan Raj, Alam K...          India

         date_added_x  release_year_x rating_x duration_x  ...  \
0  September 25, 2021            2020    PG-13     90 min  ...
1  September 24, 2021            2021    TV-MA  2 Seasons  ...
2  September 24, 2021            2021    TV-MA   1 Season  ...
3  September 24, 2021            2021    TV-MA   1 Season  ...
4  September 24, 2021            2021    TV-MA  2 Seasons  ...

                 title_y       director_y  \
0   Dick Johnson Is Dead  Kirsten Johnson
1          Blood & Water              NaN
2              Ganglands  Julien Leclercq
3  Jailbirds New Orleans              NaN
4           Kota Factory              NaN

                                              cast_y      country_y  \
0                                                NaN  United States
1  Ama Qamata, Khosi Ngema, Gail Mabalane, Thaban...   South Africa
2  Sami Bouajila, Tracy Gotoas, Samuel Jouy, Nabi...            NaN
3                                                NaN            NaN
4  Mayur More, Jitendra Kumar, Ranjan Raj, Alam K...          India

         date_added_y release_year_y rating_y duration_y  \
0  September 25, 2021           2020    PG-13     90 min
1  September 24, 2021           2021    TV-MA  2 Seasons
2  September 24, 2021           2021    TV-MA   1 Season
3  September 24, 2021           2021    TV-MA   1 Season
4  September 24, 2021           2021    TV-MA  2 Seasons

                                         listed_in_y  \
0                                      Documentaries
1    International TV Shows, TV Dramas, TV Mysteries
2  Crime TV Shows, International TV Shows, TV Act...
3                             Docuseries, Reality TV
4  International TV Shows, Romantic TV Shows, TV ...

                                       description_y
0  As her father nears the end of his life, filmm...
1  After crossing paths at a party, a Cape Town t...
2  To protect his family from a powerful drug lor...
3  Feuds, flirtations and toilet talk go down amo...
4  In a city of coaching centers known to train I...

[5 rows x 24 columns]

### Merge with condition

In [23]:
merged = pd.merge(df[df["release_year"]>2015], df, on="show_id")
print(merged.head())

  show_id   type_x                title_x       director_x  \
0      s1    Movie   Dick Johnson Is Dead  Kirsten Johnson
1      s2  TV Show          Blood & Water              NaN
2      s3  TV Show              Ganglands  Julien Leclercq
3      s4  TV Show  Jailbirds New Orleans              NaN
4      s5  TV Show           Kota Factory              NaN

                                              cast_x      country_x  \
0                                                NaN  United States
1  Ama Qamata, Khosi Ngema, Gail Mabalane, Thaban...   South Africa
2  Sami Bouajila, Tracy Gotoas, Samuel Jouy, Nabi...            NaN
3                                                NaN            NaN
4  Mayur More, Jitendra Kumar, Ranjan Raj, Alam K...          India

         date_added_x  release_year_x rating_x duration_x  ...  \
0  September 25, 2021            2020    PG-13     90 min  ...
1  September 24, 2021            2021    TV-MA  2 Seasons  ...
2  September 24, 2021            2021    TV-MA   1 Season  ...
3  September 24, 2021            2021    TV-MA   1 Season  ...
4  September 24, 2021            2021    TV-MA  2 Seasons  ...

                 title_y       director_y  \
0   Dick Johnson Is Dead  Kirsten Johnson
1          Blood & Water              NaN
2              Ganglands  Julien Leclercq
3  Jailbirds New Orleans              NaN
4           Kota Factory              NaN

                                              cast_y      country_y  \
0                                                NaN  United States
1  Ama Qamata, Khosi Ngema, Gail Mabalane, Thaban...   South Africa
2  Sami Bouajila, Tracy Gotoas, Samuel Jouy, Nabi...            NaN
3                                                NaN            NaN
4  Mayur More, Jitendra Kumar, Ranjan Raj, Alam K...          India

         date_added_y release_year_y rating_y duration_y  \
0  September 25, 2021           2020    PG-13     90 min
1  September 24, 2021           2021    TV-MA  2 Seasons
2  September 24, 2021           2021    TV-MA   1 Season
3  September 24, 2021           2021    TV-MA   1 Season
4  September 24, 2021           2021    TV-MA  2 Seasons

                                         listed_in_y  \
0                                      Documentaries
1    International TV Shows, TV Dramas, TV Mysteries
2  Crime TV Shows, International TV Shows, TV Act...
3                             Docuseries, Reality TV
4  International TV Shows, Romantic TV Shows, TV ...

                                       description_y
0  As her father nears the end of his life, filmm...
1  After crossing paths at a party, a Cape Town t...
2  To protect his family from a powerful drug lor...
3  Feuds, flirtations and toilet talk go down amo...
4  In a city of coaching centers known to train I...

[5 rows x 23 columns]

### Merge with different join keys

In [24]:
merged = pd.merge(df, df, left_on="show_id", right_on="title", how="outer")
print(merged.head())

  show_id_x type_x title_x director_x cast_x country_x date_added_x  \
0       NaN    NaN     NaN        NaN    NaN       NaN          NaN
1       NaN    NaN     NaN        NaN    NaN       NaN          NaN
2       NaN    NaN     NaN        NaN    NaN       NaN          NaN
3       NaN    NaN     NaN        NaN    NaN       NaN          NaN
4       NaN    NaN     NaN        NaN    NaN       NaN          NaN

   release_year_x rating_x duration_x  ...                        title_y  \
0             NaN      NaN        NaN  ...                         #Alive
1             NaN      NaN        NaN  ...  #AnneFrank - Parallel Stories
2             NaN      NaN        NaN  ...              #FriendButMarried
3             NaN      NaN        NaN  ...            #FriendButMarried 2
4             NaN      NaN        NaN  ...                          #Roxy

                    director_y  \
0                       Cho Il
1  Sabina Fedeli, Anna Migotto
2                Rako Prijanto
3                Rako Prijanto
4              Michael Kennedy

                                              cast_y    country_y  \
0                           Yoo Ah-in, Park Shin-hye  South Korea
1                        Helen Mirren, Gengher Gatti        Italy
2  Adipati Dolken, Vanesha Prescilla, Rendi Jhon,...    Indonesia
3  Adipati Dolken, Mawar de Jongh, Sari Nila, Von...    Indonesia
4  Jake Short, Sarah Fisher, Booboo Stewart, Dann...       Canada

        date_added_y release_year_y rating_y duration_y  \
0  September 8, 2020         2020.0    TV-MA     99 min
1       July 1, 2020         2019.0    TV-14     95 min
2       May 21, 2020         2018.0     TV-G    102 min
3      June 28, 2020         2020.0     TV-G    104 min
4     April 10, 2019         2018.0    TV-14    105 min

                                      listed_in_y  \
0  Horror Movies, International Movies, Thrillers
1             Documentaries, International Movies
2   Dramas, International Movies, Romantic Movies
3   Dramas, International Movies, Romantic Movies
4                       Comedies, Romantic Movies

                                       description_y
0  As a grisly virus rampages a city, a lone man ...
1  Through her diary, Anne Frank's story is retol...
2  Pining for his high school crush for years, a ...
3  As Ayu and Ditto finally transition from best ...
4  A teenage hacker with a huge nose helps a cool...

[5 rows x 24 columns]

### Merge and select columns

In [25]:
merged = pd.merge(df, df, on="show_id")[["show_id","title_x","title_y"]]
print(merged.head())

  show_id                title_x                title_y
0      s1   Dick Johnson Is Dead   Dick Johnson Is Dead
1      s2          Blood & Water          Blood & Water
2      s3              Ganglands              Ganglands
3      s4  Jailbirds New Orleans  Jailbirds New Orleans
4      s5           Kota Factory           Kota Factory

### Merge multiple DataFrames

In [26]:
df1 = df[["show_id","title"]]
df2 = df[["show_id","director"]]
df3 = df[["show_id","country"]]
merged = df1.merge(df2,on="show_id").merge(df3,on="show_id")
print(merged.head())

  show_id                  title         director        country
0      s1   Dick Johnson Is Dead  Kirsten Johnson  United States
1      s2          Blood & Water              NaN   South Africa
2      s3              Ganglands  Julien Leclercq            NaN
3      s4  Jailbirds New Orleans              NaN            NaN
4      s5           Kota Factory              NaN          India

## 1.2 Join

### Simple join on index

In [27]:
joined = df.set_index("show_id").join(df.set_index("show_id"), lsuffix="_A", rsuffix="_B")
print(joined.head())

          type_A                title_A       director_A  \
show_id
s1         Movie   Dick Johnson Is Dead  Kirsten Johnson
s2       TV Show          Blood & Water              NaN
s3       TV Show              Ganglands  Julien Leclercq
s4       TV Show  Jailbirds New Orleans              NaN
s5       TV Show           Kota Factory              NaN

                                                    cast_A      country_A  \
show_id
s1                                                     NaN  United States
s2       Ama Qamata, Khosi Ngema, Gail Mabalane, Thaban...   South Africa
s3       Sami Bouajila, Tracy Gotoas, Samuel Jouy, Nabi...            NaN
s4                                                     NaN            NaN
s5       Mayur More, Jitendra Kumar, Ranjan Raj, Alam K...          India

               date_added_A  release_year_A rating_A duration_A  \
show_id
s1       September 25, 2021            2020    PG-13     90 min
s2       September 24, 2021            2021    TV-MA  2 Seasons
s3       September 24, 2021            2021    TV-MA   1 Season
s4       September 24, 2021            2021    TV-MA   1 Season
s5       September 24, 2021            2021    TV-MA  2 Seasons

                                               listed_in_A  ...  \
show_id                                                     ...
s1                                           Documentaries  ...
s2         International TV Shows, TV Dramas, TV Mysteries  ...
s3       Crime TV Shows, International TV Shows, TV Act...  ...
s4                                  Docuseries, Reality TV  ...
s5       International TV Shows, Romantic TV Shows, TV ...  ...

                       title_B       director_B  \
show_id
s1        Dick Johnson Is Dead  Kirsten Johnson
s2               Blood & Water              NaN
s3                   Ganglands  Julien Leclercq
s4       Jailbirds New Orleans              NaN
s5                Kota Factory              NaN

                                                    cast_B      country_B  \
show_id
s1                                                     NaN  United States
s2       Ama Qamata, Khosi Ngema, Gail Mabalane, Thaban...   South Africa
s3       Sami Bouajila, Tracy Gotoas, Samuel Jouy, Nabi...            NaN
s4                                                     NaN            NaN
s5       Mayur More, Jitendra Kumar, Ranjan Raj, Alam K...          India

               date_added_B release_year_B rating_B  duration_B  \
show_id
s1       September 25, 2021           2020    PG-13      90 min
s2       September 24, 2021           2021    TV-MA   2 Seasons
s3       September 24, 2021           2021    TV-MA    1 Season
s4       September 24, 2021           2021    TV-MA    1 Season
s5       September 24, 2021           2021    TV-MA   2 Seasons

                                               listed_in_B  \
show_id
s1                                           Documentaries
s2         International TV Shows, TV Dramas, TV Mysteries
s3       Crime TV Shows, International TV Shows, TV Act...
s4                                  Docuseries, Reality TV
s5       International TV Shows, Romantic TV Shows, TV ...

                                             description_B
show_id
s1       As her father nears the end of his life, filmm...
s2       After crossing paths at a party, a Cape Town t...
s3       To protect his family from a powerful drug lor...
s4       Feuds, flirtations and toilet talk go down amo...
s5       In a city of coaching centers known to train I...

[5 rows x 22 columns]

### Left join

In [28]:
df1.join(df2, how='left', lsuffix='_df1', rsuffix='_df2')

     show_id_df1                  title show_id_df2         director
0             s1   Dick Johnson Is Dead          s1  Kirsten Johnson
1             s2          Blood & Water          s2              NaN
2             s3              Ganglands          s3  Julien Leclercq
3             s4  Jailbirds New Orleans          s4              NaN
4             s5           Kota Factory          s5              NaN
...          ...                    ...         ...              ...
8802       s8803                 Zodiac       s8803    David Fincher
8803       s8804            Zombie Dumb       s8804              NaN
8804       s8805             Zombieland       s8805  Ruben Fleischer
8805       s8806                   Zoom       s8806     Peter Hewitt
8806       s8807                 Zubaan       s8807      Mozez Singh

[8807 rows x 4 columns]

### Right Join

In [29]:
df1.join(df2, how='right', lsuffix='_df1', rsuffix='_df2')

     show_id_df1                  title show_id_df2         director
0             s1   Dick Johnson Is Dead          s1  Kirsten Johnson
1             s2          Blood & Water          s2              NaN
2             s3              Ganglands          s3  Julien Leclercq
3             s4  Jailbirds New Orleans          s4              NaN
4             s5           Kota Factory          s5              NaN
...          ...                    ...         ...              ...
8802       s8803                 Zodiac       s8803    David Fincher
8803       s8804            Zombie Dumb       s8804              NaN
8804       s8805             Zombieland       s8805  Ruben Fleischer
8805       s8806                   Zoom       s8806     Peter Hewitt
8806       s8807                 Zubaan       s8807      Mozez Singh

[8807 rows x 4 columns]

### Outer Join

In [30]:
df1.join(df2, how='outer', lsuffix='_df1', rsuffix='_df2')

     show_id_df1                  title show_id_df2         director
0             s1   Dick Johnson Is Dead          s1  Kirsten Johnson
1             s2          Blood & Water          s2              NaN
2             s3              Ganglands          s3  Julien Leclercq
3             s4  Jailbirds New Orleans          s4              NaN
4             s5           Kota Factory          s5              NaN
...          ...                    ...         ...              ...
8802       s8803                 Zodiac       s8803    David Fincher
8803       s8804            Zombie Dumb       s8804              NaN
8804       s8805             Zombieland       s8805  Ruben Fleischer
8805       s8806                   Zoom       s8806     Peter Hewitt
8806       s8807                 Zubaan       s8807      Mozez Singh

[8807 rows x 4 columns]

###  Inner Join

In [31]:
df1.join(df2, how='inner', lsuffix='_df1', rsuffix='_df2')

     show_id_df1                  title show_id_df2         director
0             s1   Dick Johnson Is Dead          s1  Kirsten Johnson
1             s2          Blood & Water          s2              NaN
2             s3              Ganglands          s3  Julien Leclercq
3             s4  Jailbirds New Orleans          s4              NaN
4             s5           Kota Factory          s5              NaN
...          ...                    ...         ...              ...
8802       s8803                 Zodiac       s8803    David Fincher
8803       s8804            Zombie Dumb       s8804              NaN
8804       s8805             Zombieland       s8805  Ruben Fleischer
8805       s8806                   Zoom       s8806     Peter Hewitt
8806       s8807                 Zubaan       s8807      Mozez Singh

[8807 rows x 4 columns]

###  Join with Suffixes (explicit)

In [32]:
df1.join(df2, lsuffix='_left', rsuffix='_right')

     show_id_left                  title show_id_right         director
0              s1   Dick Johnson Is Dead            s1  Kirsten Johnson
1              s2          Blood & Water            s2              NaN
2              s3              Ganglands            s3  Julien Leclercq
3              s4  Jailbirds New Orleans            s4              NaN
4              s5           Kota Factory            s5              NaN
...           ...                    ...           ...              ...
8802        s8803                 Zodiac         s8803    David Fincher
8803        s8804            Zombie Dumb         s8804              NaN
8804        s8805             Zombieland         s8805  Ruben Fleischer
8805        s8806                   Zoom         s8806     Peter Hewitt
8806        s8807                 Zubaan         s8807      Mozez Singh

[8807 rows x 4 columns]

### Join Multiple DataFrames

In [33]:
df_temp = df1.join(df2, lsuffix='_df1', rsuffix='_df2')
df_result = df_temp.join(pd.DataFrame({'country':['US','UK','IN']}, index=[1,2,3]))
print(df_result)

     show_id_df1                  title show_id_df2         director country
0             s1   Dick Johnson Is Dead          s1  Kirsten Johnson     NaN
1             s2          Blood & Water          s2              NaN      US
2             s3              Ganglands          s3  Julien Leclercq      UK
3             s4  Jailbirds New Orleans          s4              NaN      IN
4             s5           Kota Factory          s5              NaN     NaN
...          ...                    ...         ...              ...     ...
8802       s8803                 Zodiac       s8803    David Fincher     NaN
8803       s8804            Zombie Dumb       s8804              NaN     NaN
8804       s8805             Zombieland       s8805  Ruben Fleischer     NaN
8805       s8806                   Zoom       s8806     Peter Hewitt     NaN
8806       s8807                 Zubaan       s8807      Mozez Singh     NaN

[8807 rows x 5 columns]

 ### Join with Reindex

In [34]:
df1.join(df2.reindex([1,2,3]), lsuffix='_df1', rsuffix='_df2')

     show_id_df1                  title show_id_df2         director
0             s1   Dick Johnson Is Dead         NaN              NaN
1             s2          Blood & Water          s2              NaN
2             s3              Ganglands          s3  Julien Leclercq
3             s4  Jailbirds New Orleans          s4              NaN
4             s5           Kota Factory         NaN              NaN
...          ...                    ...         ...              ...
8802       s8803                 Zodiac         NaN              NaN
8803       s8804            Zombie Dumb         NaN              NaN
8804       s8805             Zombieland         NaN              NaN
8805       s8806                   Zoom         NaN              NaN
8806       s8807                 Zubaan         NaN              NaN

[8807 rows x 4 columns]

### Join with Selected Columns

In [35]:
df1.join(df2[['director']], lsuffix='_df1', rsuffix='_df2')

     show_id                  title         director
0         s1   Dick Johnson Is Dead  Kirsten Johnson
1         s2          Blood & Water              NaN
2         s3              Ganglands  Julien Leclercq
3         s4  Jailbirds New Orleans              NaN
4         s5           Kota Factory              NaN
...      ...                    ...              ...
8802   s8803                 Zodiac    David Fincher
8803   s8804            Zombie Dumb              NaN
8804   s8805             Zombieland  Ruben Fleischer
8805   s8806                   Zoom     Peter Hewitt
8806   s8807                 Zubaan      Mozez Singh

[8807 rows x 3 columns]

### Join with Overlapping Index

In [36]:
df1.join(df2, how='outer', lsuffix='_df1', rsuffix='_df2')

     show_id_df1                  title show_id_df2         director
0             s1   Dick Johnson Is Dead          s1  Kirsten Johnson
1             s2          Blood & Water          s2              NaN
2             s3              Ganglands          s3  Julien Leclercq
3             s4  Jailbirds New Orleans          s4              NaN
4             s5           Kota Factory          s5              NaN
...          ...                    ...         ...              ...
8802       s8803                 Zodiac       s8803    David Fincher
8803       s8804            Zombie Dumb       s8804              NaN
8804       s8805             Zombieland       s8805  Ruben Fleischer
8805       s8806                   Zoom       s8806     Peter Hewitt
8806       s8807                 Zubaan       s8807      Mozez Singh

[8807 rows x 4 columns]

### Join with Reset Index

In [37]:
df1.reset_index().join(df2.reset_index(), lsuffix='_l', rsuffix='_r')

,index_l,show_id_l,title,index_r,show_id_r,director
0,0,s1,Dick Johnson Is Dead,0,s1,Kirsten Johnson
1,1,s2,Blood & Water,1,s2,NaN
2,2,s3,Ganglands,2,s3,Julien Leclercq
3,3,s4,Jailbirds New Orleans,3,s4,NaN
4,4,s5,Kota Factory,4,s5,NaN
...,...,...,...,...,...,...
8802,8802,s8803,Zodiac,8802,s8803,David Fincher
8803,8803,s8804,Zombie Dumb,8803,s8804,NaN
8804,8804,s8805,Zombieland,8804,s8805,Ruben Fleischer
8805,8805,s8806,Zoom,8805,s8806,Peter Hewitt
8806,8806,s8807,Zubaan,8806,s8807,Mozez Singh

### Join with Multi-Index

In [38]:
# Example: create a custom index of the same length
df1 = df1.set_index(pd.RangeIndex(start=1, stop=len(df1)+1))
df2 = df2.set_index(pd.RangeIndex(start=1, stop=len(df2)+1))

# Now join safely with suffixes
df1.join(df2, lsuffix='_df1', rsuffix='_df2')

     show_id_df1                  title show_id_df2         director
1             s1   Dick Johnson Is Dead          s1  Kirsten Johnson
2             s2          Blood & Water          s2              NaN
3             s3              Ganglands          s3  Julien Leclercq
4             s4  Jailbirds New Orleans          s4              NaN
5             s5           Kota Factory          s5              NaN
...          ...                    ...         ...              ...
8803       s8803                 Zodiac       s8803    David Fincher
8804       s8804            Zombie Dumb       s8804              NaN
8805       s8805             Zombieland       s8805  Ruben Fleischer
8806       s8806                   Zoom       s8806     Peter Hewitt
8807       s8807                 Zubaan       s8807      Mozez Singh

[8807 rows x 4 columns]

### Join with Filtered Data

In [39]:
df1.join(df2[df2['director']=='Dir2'], lsuffix='_df1', rsuffix='_df2')

     show_id_df1                  title show_id_df2 director
1             s1   Dick Johnson Is Dead         NaN      NaN
2             s2          Blood & Water         NaN      NaN
3             s3              Ganglands         NaN      NaN
4             s4  Jailbirds New Orleans         NaN      NaN
5             s5           Kota Factory         NaN      NaN
...          ...                    ...         ...      ...
8803       s8803                 Zodiac         NaN      NaN
8804       s8804            Zombie Dumb         NaN      NaN
8805       s8805             Zombieland         NaN      NaN
8806       s8806                   Zoom         NaN      NaN
8807       s8807                 Zubaan         NaN      NaN

[8807 rows x 4 columns]

### Join with Query

In [40]:
df1.join(df2.query("director=='Dir1'"), lsuffix='_df1', rsuffix='_df2')

     show_id_df1                  title show_id_df2 director
1             s1   Dick Johnson Is Dead         NaN      NaN
2             s2          Blood & Water         NaN      NaN
3             s3              Ganglands         NaN      NaN
4             s4  Jailbirds New Orleans         NaN      NaN
5             s5           Kota Factory         NaN      NaN
...          ...                    ...         ...      ...
8803       s8803                 Zodiac         NaN      NaN
8804       s8804            Zombie Dumb         NaN      NaN
8805       s8805             Zombieland         NaN      NaN
8806       s8806                   Zoom         NaN      NaN
8807       s8807                 Zubaan         NaN      NaN

[8807 rows x 4 columns]

### Join with Sorted Index

In [41]:
df1.join(df2.query("director=='Dir1'"), lsuffix='_df1', rsuffix='_df2')

     show_id_df1                  title show_id_df2 director
1             s1   Dick Johnson Is Dead         NaN      NaN
2             s2          Blood & Water         NaN      NaN
3             s3              Ganglands         NaN      NaN
4             s4  Jailbirds New Orleans         NaN      NaN
5             s5           Kota Factory         NaN      NaN
...          ...                    ...         ...      ...
8803       s8803                 Zodiac         NaN      NaN
8804       s8804            Zombie Dumb         NaN      NaN
8805       s8805             Zombieland         NaN      NaN
8806       s8806                   Zoom         NaN      NaN
8807       s8807                 Zubaan         NaN      NaN

[8807 rows x 4 columns]

## 1.3 Concatenate

###  Row-wise Concatenation

In [42]:
pd.concat([df1, df2])

     show_id                  title         director
1         s1   Dick Johnson Is Dead              NaN
2         s2          Blood & Water              NaN
3         s3              Ganglands              NaN
4         s4  Jailbirds New Orleans              NaN
5         s5           Kota Factory              NaN
...      ...                    ...              ...
8803   s8803                    NaN    David Fincher
8804   s8804                    NaN              NaN
8805   s8805                    NaN  Ruben Fleischer
8806   s8806                    NaN     Peter Hewitt
8807   s8807                    NaN      Mozez Singh

[17614 rows x 3 columns]

###  Column-wise Concatenation

In [43]:
pd.concat([df1, df2], axis=1)

     show_id                  title show_id         director
1         s1   Dick Johnson Is Dead      s1  Kirsten Johnson
2         s2          Blood & Water      s2              NaN
3         s3              Ganglands      s3  Julien Leclercq
4         s4  Jailbirds New Orleans      s4              NaN
5         s5           Kota Factory      s5              NaN
...      ...                    ...     ...              ...
8803   s8803                 Zodiac   s8803    David Fincher
8804   s8804            Zombie Dumb   s8804              NaN
8805   s8805             Zombieland   s8805  Ruben Fleischer
8806   s8806                   Zoom   s8806     Peter Hewitt
8807   s8807                 Zubaan   s8807      Mozez Singh

[8807 rows x 4 columns]

###  Concatenate and Ignore Index

In [44]:
pd.concat([df1, df2], ignore_index=True)

      show_id                  title         director
0          s1   Dick Johnson Is Dead              NaN
1          s2          Blood & Water              NaN
2          s3              Ganglands              NaN
3          s4  Jailbirds New Orleans              NaN
4          s5           Kota Factory              NaN
...       ...                    ...              ...
17609   s8803                    NaN    David Fincher
17610   s8804                    NaN              NaN
17611   s8805                    NaN  Ruben Fleischer
17612   s8806                    NaN     Peter Hewitt
17613   s8807                    NaN      Mozez Singh

[17614 rows x 3 columns]

###   Concatenate with Keys

In [45]:
pd.concat([df1, df2], keys=['first','second'])

            show_id                  title         director
first  1         s1   Dick Johnson Is Dead              NaN
       2         s2          Blood & Water              NaN
       3         s3              Ganglands              NaN
       4         s4  Jailbirds New Orleans              NaN
       5         s5           Kota Factory              NaN
...             ...                    ...              ...
second 8803   s8803                    NaN    David Fincher
       8804   s8804                    NaN              NaN
       8805   s8805                    NaN  Ruben Fleischer
       8806   s8806                    NaN     Peter Hewitt
       8807   s8807                    NaN      Mozez Singh

[17614 rows x 3 columns]

###   Concatenate with Integrity Check

In [46]:
pd.concat([df1, df2], keys=['first','second'])

            show_id                  title         director
first  1         s1   Dick Johnson Is Dead              NaN
       2         s2          Blood & Water              NaN
       3         s3              Ganglands              NaN
       4         s4  Jailbirds New Orleans              NaN
       5         s5           Kota Factory              NaN
...             ...                    ...              ...
second 8803   s8803                    NaN    David Fincher
       8804   s8804                    NaN              NaN
       8805   s8805                    NaN  Ruben Fleischer
       8806   s8806                    NaN     Peter Hewitt
       8807   s8807                    NaN      Mozez Singh

[17614 rows x 3 columns]

###   Concatenate with Series

In [47]:
pd.concat([df1, pd.Series(['US','UK'], name='country')], axis=1)

     show_id                  title country
1         s1   Dick Johnson Is Dead      UK
2         s2          Blood & Water     NaN
3         s3              Ganglands     NaN
4         s4  Jailbirds New Orleans     NaN
5         s5           Kota Factory     NaN
...      ...                    ...     ...
8804   s8804            Zombie Dumb     NaN
8805   s8805             Zombieland     NaN
8806   s8806                   Zoom     NaN
8807   s8807                 Zubaan     NaN
0        NaN                    NaN      US

[8808 rows x 3 columns]

###   Concatenate with Dictionary

In [48]:
pd.concat({'df1':df1, 'df2':df2})

         show_id                  title         director
df1 1         s1   Dick Johnson Is Dead              NaN
    2         s2          Blood & Water              NaN
    3         s3              Ganglands              NaN
    4         s4  Jailbirds New Orleans              NaN
    5         s5           Kota Factory              NaN
...          ...                    ...              ...
df2 8803   s8803                    NaN    David Fincher
    8804   s8804                    NaN              NaN
    8805   s8805                    NaN  Ruben Fleischer
    8806   s8806                    NaN     Peter Hewitt
    8807   s8807                    NaN      Mozez Singh

[17614 rows x 3 columns]

###  Concatenate with Reindex

In [49]:
pd.concat({'df1':df1, 'df2':df2})

         show_id                  title         director
df1 1         s1   Dick Johnson Is Dead              NaN
    2         s2          Blood & Water              NaN
    3         s3              Ganglands              NaN
    4         s4  Jailbirds New Orleans              NaN
    5         s5           Kota Factory              NaN
...          ...                    ...              ...
df2 8803   s8803                    NaN    David Fincher
    8804   s8804                    NaN              NaN
    8805   s8805                    NaN  Ruben Fleischer
    8806   s8806                    NaN     Peter Hewitt
    8807   s8807                    NaN      Mozez Singh

[17614 rows x 3 columns]

###   Concatenate Different Columns

In [50]:
pd.concat([df1, pd.DataFrame({'director':['Dir1','Dir2']})], axis=1)

     show_id                  title director
1         s1   Dick Johnson Is Dead     Dir2
2         s2          Blood & Water      NaN
3         s3              Ganglands      NaN
4         s4  Jailbirds New Orleans      NaN
5         s5           Kota Factory      NaN
...      ...                    ...      ...
8804   s8804            Zombie Dumb      NaN
8805   s8805             Zombieland      NaN
8806   s8806                   Zoom      NaN
8807   s8807                 Zubaan      NaN
0        NaN                    NaN     Dir1

[8808 rows x 3 columns]

###  Concatenate with Duplicates

In [51]:
pd.concat([df1, pd.DataFrame({'director':['Dir1','Dir2']})], axis=1)

     show_id                  title director
1         s1   Dick Johnson Is Dead     Dir2
2         s2          Blood & Water      NaN
3         s3              Ganglands      NaN
4         s4  Jailbirds New Orleans      NaN
5         s5           Kota Factory      NaN
...      ...                    ...      ...
8804   s8804            Zombie Dumb      NaN
8805   s8805             Zombieland      NaN
8806   s8806                   Zoom      NaN
8807   s8807                 Zubaan      NaN
0        NaN                    NaN     Dir1

[8808 rows x 3 columns]

###   Concatenate with Sort

In [52]:
pd.concat([df1, df2], sort=True)

             director show_id                  title
1                 NaN      s1   Dick Johnson Is Dead
2                 NaN      s2          Blood & Water
3                 NaN      s3              Ganglands
4                 NaN      s4  Jailbirds New Orleans
5                 NaN      s5           Kota Factory
...               ...     ...                    ...
8803    David Fincher   s8803                    NaN
8804              NaN   s8804                    NaN
8805  Ruben Fleischer   s8805                    NaN
8806     Peter Hewitt   s8806                    NaN
8807      Mozez Singh   s8807                    NaN

[17614 rows x 3 columns]

###   Concatenate with Multi-Level Keys

In [53]:
pd.concat([df1, df2], sort=True)

             director show_id                  title
1                 NaN      s1   Dick Johnson Is Dead
2                 NaN      s2          Blood & Water
3                 NaN      s3              Ganglands
4                 NaN      s4  Jailbirds New Orleans
5                 NaN      s5           Kota Factory
...               ...     ...                    ...
8803    David Fincher   s8803                    NaN
8804              NaN   s8804                    NaN
8805  Ruben Fleischer   s8805                    NaN
8806     Peter Hewitt   s8806                    NaN
8807      Mozez Singh   s8807                    NaN

[17614 rows x 3 columns]

###  Concatenate with Filtered Data

In [54]:
pd.concat([df1[df1['show_id']==1], df2])

     show_id title         director
1         s1   NaN  Kirsten Johnson
2         s2   NaN              NaN
3         s3   NaN  Julien Leclercq
4         s4   NaN              NaN
5         s5   NaN              NaN
...      ...   ...              ...
8803   s8803   NaN    David Fincher
8804   s8804   NaN              NaN
8805   s8805   NaN  Ruben Fleischer
8806   s8806   NaN     Peter Hewitt
8807   s8807   NaN      Mozez Singh

[8807 rows x 3 columns]

### Concatenate with Reset Index

In [55]:
pd.concat([df1[df1['show_id']==1], df2])

     show_id title         director
1         s1   NaN  Kirsten Johnson
2         s2   NaN              NaN
3         s3   NaN  Julien Leclercq
4         s4   NaN              NaN
5         s5   NaN              NaN
...      ...   ...              ...
8803   s8803   NaN    David Fincher
8804   s8804   NaN              NaN
8805   s8805   NaN  Ruben Fleischer
8806   s8806   NaN     Peter Hewitt
8807   s8807   NaN      Mozez Singh

[8807 rows x 3 columns]

## 1.4 COMBINE

### Combine rating column and fill missing values

In [56]:
df['rating'].combine_first(df['rating'])

0       PG-13
1       TV-MA
2       TV-MA
3       TV-MA
4       TV-MA
        ...
8802        R
8803    TV-Y7
8804        R
8805       PG
8806    TV-14
Name: rating, Length: 8807, dtype: str

   ### Combine country column values

In [57]:
df['country'].combine_first(df['country'])

0       United States
1        South Africa
2                 NaN
3                 NaN
4               India
            ...
8802    United States
8803              NaN
8804    United States
8805    United States
8806            India
Name: country, Length: 8807, dtype: str

### Combine duration values

In [58]:
df['duration'].combine_first(df['duration'])

0          90 min
1       2 Seasons
2        1 Season
3        1 Season
4       2 Seasons
          ...
8802      158 min
8803    2 Seasons
8804       88 min
8805       88 min
8806      111 min
Name: duration, Length: 8807, dtype: str

### Combine listed_in values

In [59]:
df['listed_in'].combine_first(df['listed_in'])

0                                           Documentaries
1         International TV Shows, TV Dramas, TV Mysteries
2       Crime TV Shows, International TV Shows, TV Act...
3                                  Docuseries, Reality TV
4       International TV Shows, Romantic TV Shows, TV ...
                              ...
8802                       Cult Movies, Dramas, Thrillers
8803               Kids' TV, Korean TV Shows, TV Comedies
8804                              Comedies, Horror Movies
8805                   Children & Family Movies, Comedies
8806       Dramas, International Movies, Music & Musicals
Name: listed_in, Length: 8807, dtype: str

### Combine description values

In [60]:
df['description'].combine_first(df['description'])

0       As her father nears the end of his life, filmm...
1       After crossing paths at a party, a Cape Town t...
2       To protect his family from a powerful drug lor...
3       Feuds, flirtations and toilet talk go down amo...
4       In a city of coaching centers known to train I...
                              ...
8802    A political cartoonist, a crime reporter and a...
8803    While living alone in a spooky town, a young g...
8804    Looking to survive in a world taken over by zo...
8805    Dragged from civilian life, a former superhero...
8806    A scrappy but poor boy worms his way into a ty...
Name: description, Length: 8807, dtype: str

### Combine director values

In [61]:
df['director'].combine_first(df['director'])

0       Kirsten Johnson
1                   NaN
2       Julien Leclercq
3                   NaN
4                   NaN
             ...
8802      David Fincher
8803                NaN
8804    Ruben Fleischer
8805       Peter Hewitt
8806        Mozez Singh
Name: director, Length: 8807, dtype: str

### Combine cast value

In [62]:
df['cast'].combine_first(df['cast'])

0                                                     NaN
1       Ama Qamata, Khosi Ngema, Gail Mabalane, Thaban...
2       Sami Bouajila, Tracy Gotoas, Samuel Jouy, Nabi...
3                                                     NaN
4       Mayur More, Jitendra Kumar, Ranjan Raj, Alam K...
                              ...
8802    Mark Ruffalo, Jake Gyllenhaal, Robert Downey J...
8803                                                  NaN
8804    Jesse Eisenberg, Woody Harrelson, Emma Stone, ...
8805    Tim Allen, Courteney Cox, Chevy Chase, Kate Ma...
8806    Vicky Kaushal, Sarah-Jane Dias, Raaghav Chanan...
Name: cast, Length: 8807, dtype: str

### Combine release_year values

In [63]:
df['release_year'].combine_first(df['release_year'])

0       2020
1       2021
2       2021
3       2021
4       2021
        ...
8802    2007
8803    2018
8804    2009
8805    2006
8806    2015
Name: release_year, Length: 8807, dtype: int64

### Combine type values#

In [64]:
df['type'].combine_first(df['type'])

0         Movie
1       TV Show
2       TV Show
3       TV Show
4       TV Show
         ...
8802      Movie
8803    TV Show
8804      Movie
8805      Movie
8806      Movie
Name: type, Length: 8807, dtype: str

### Combine rating with custom function

In [65]:
df['rating'].combine(df['rating'], lambda x,y:x)

0       PG-13
1       TV-MA
2       TV-MA
3       TV-MA
4       TV-MA
        ...
8802        R
8803    TV-Y7
8804        R
8805       PG
8806    TV-14
Name: rating, Length: 8807, dtype: str

### Combine duration using custom logic

In [66]:
df['duration'].combine(df['duration'], lambda x,y:y)

0          90 min
1       2 Seasons
2        1 Season
3        1 Season
4       2 Seasons
          ...
8802      158 min
8803    2 Seasons
8804       88 min
8805       88 min
8806      111 min
Name: duration, Length: 8807, dtype: str

### Combine release year average

In [67]:
df['release_year'].combine(df['release_year'], lambda x,y:(x+y)/2)

0       2020.0
1       2021.0
2       2021.0
3       2021.0
4       2021.0
         ...
8802    2007.0
8803    2018.0
8804    2009.0
8805    2006.0
8806    2015.0
Name: release_year, Length: 8807, dtype: float64

### Combine country conditionally

In [68]:
df['country'].combine(df['country'], lambda x,y:x)

0       United States
1        South Africa
2                 NaN
3                 NaN
4               India
            ...
8802    United States
8803              NaN
8804    United States
8805    United States
8806            India
Name: country, Length: 8807, dtype: str

### Combine genre values

In [69]:
df['listed_in'].combine(df['listed_in'], lambda x,y:y)

0                                           Documentaries
1         International TV Shows, TV Dramas, TV Mysteries
2       Crime TV Shows, International TV Shows, TV Act...
3                                  Docuseries, Reality TV
4       International TV Shows, Romantic TV Shows, TV ...
                              ...
8802                       Cult Movies, Dramas, Thrillers
8803               Kids' TV, Korean TV Shows, TV Comedies
8804                              Comedies, Horror Movies
8805                   Children & Family Movies, Comedies
8806       Dramas, International Movies, Music & Musicals
Name: listed_in, Length: 8807, dtype: str

## 1.5 RESHAPE

### 1. Melt title and country columns

In [70]:
pd.melt(df,
id_vars=['show_id'],
value_vars=['title','country'])

      show_id variable                  value
0          s1    title   Dick Johnson Is Dead
1          s2    title          Blood & Water
2          s3    title              Ganglands
3          s4    title  Jailbirds New Orleans
4          s5    title           Kota Factory
...       ...      ...                    ...
17609   s8803  country          United States
17610   s8804  country                    NaN
17611   s8805  country          United States
17612   s8806  country          United States
17613   s8807  country                  India

[17614 rows x 3 columns]

### Melt rating and duration

In [71]:
pd.melt(df,
id_vars=['show_id'],
value_vars=['rating','duration'])

      show_id  variable      value
0          s1    rating      PG-13
1          s2    rating      TV-MA
2          s3    rating      TV-MA
3          s4    rating      TV-MA
4          s5    rating      TV-MA
...       ...       ...        ...
17609   s8803  duration    158 min
17610   s8804  duration  2 Seasons
17611   s8805  duration     88 min
17612   s8806  duration     88 min
17613   s8807  duration    111 min

[17614 rows x 3 columns]

### Stack title and country

In [72]:
df[['title','country']].stack()

0     title      Dick Johnson Is Dead
      country           United States
1     title             Blood & Water
      country            South Africa
2     title                 Ganglands
                         ...
8804  country           United States
8805  title                      Zoom
      country           United States
8806  title                    Zubaan
      country                   India
Length: 17614, dtype: str

### Unstack stacked data

In [73]:
df[['title','country']].stack().unstack()

                      title        country
0      Dick Johnson Is Dead  United States
1             Blood & Water   South Africa
2                 Ganglands            NaN
3     Jailbirds New Orleans            NaN
4              Kota Factory          India
...                     ...            ...
8802                 Zodiac  United States
8803            Zombie Dumb            NaN
8804             Zombieland  United States
8805                   Zoom  United States
8806                 Zubaan          India

[8807 rows x 2 columns]

### Transpose dataset

In [74]:
df[['title','country']].T

,0,1,2,3,4,5,6,7,8,9,...,8797,8798,8799,8800,8801,8802,8803,8804,8805,8806
title,Dick Johnson Is Dead,Blood & Water,Ganglands,Jailbirds New Orleans,Kota Factory,Midnight Mass,My Little Pony: A New Generation,Sankofa,The Great British Baking Show,The Starling,...,Zak Storm,Zed Plus,Zenda,Zindagi Gulzar Hai,Zinzana,Zodiac,Zombie Dumb,Zombieland,Zoom,Zubaan
country,United States,South Africa,NaN,NaN,India,NaN,NaN,"United States, Ghana, Burkina Faso, United Kin...",United Kingdom,United States,...,"United States, France, South Korea, Indonesia",India,India,Pakistan,"United Arab Emirates, Jordan",United States,NaN,United States,United States,India

### Set show_id as index

In [75]:
df.set_index('show_id')

,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
show_id,,,,,,,,,,,
s1,Movie,Dick Johnson Is Dead,Kirsten Johnson,NaN,United States,"September 25, 2021",2020,PG-13,90 min,Documentaries,"As her father nears the end of his life, filmm..."
s2,TV Show,Blood & Water,NaN,"Ama Qamata, Khosi Ngema, Gail Mabalane, Thaban...",South Africa,"September 24, 2021",2021,TV-MA,2 Seasons,"International TV Shows, TV Dramas, TV Mysteries","After crossing paths at a party, a Cape Town t..."
s3,TV Show,Ganglands,Julien Leclercq,"Sami Bouajila, Tracy Gotoas, Samuel Jouy, Nabi...",NaN,"September 24, 2021",2021,TV-MA,1 Season,"Crime TV Shows, International TV Shows, TV Act...",To protect his family from a powerful drug lor...
s4,TV Show,Jailbirds New Orleans,NaN,NaN,NaN,"September 24, 2021",2021,TV-MA,1 Season,"Docuseries, Reality TV","Feuds, flirtations and toilet talk go down amo..."
s5,TV Show,Kota Factory,NaN,"Mayur More, Jitendra Kumar, Ranjan Raj, Alam K...",India,"September 24, 2021",2021,TV-MA,2 Seasons,"International TV Shows, Romantic TV Shows, TV ...",In a city of coaching centers known to train I...
...,...,...,...,...,...,...,...,...,...,...,...
s8803,Movie,Zodiac,David Fincher,"Mark Ruffalo, Jake Gyllenhaal, Robert Downey J...",United States,"November 20, 2019",2007,R,158 min,"Cult Movies, Dramas, Thrillers","A political cartoonist, a crime reporter and a..."
s8804,TV Show,Zombie Dumb,NaN,NaN,NaN,"July 1, 2019",2018,TV-Y7,2 Seasons,"Kids' TV, Korean TV Shows, TV Comedies","While living alone in a spooky town, a young g..."
s8805,Movie,Zombieland,Ruben Fleischer,"Jesse Eisenberg, Woody Harrelson, Emma Stone, ...",United States,"November 1, 2019",2009,R,88 min,"Comedies, Horror Movies",Looking to survive in a world taken over by zo...
s8806,Movie,Zoom,Peter Hewitt,"Tim Allen, Courteney Cox, Chevy Chase, Kate Ma...",United States,"January 11, 2020",2006,PG,88 min,"Children & Family Movies, Comedies","Dragged from civilian life, a former superhero..."
s8807,Movie,Zubaan,Mozez Singh,"Vicky Kaushal, Sarah-Jane Dias, Raaghav Chanan...",India,"March 2, 2019",2015,TV-14,111 min,"Dramas, International Movies, Music & Musicals",A scrappy but poor boy worms his way into a ty...

### Reset index

In [76]:
df.reset_index()

,index,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
0,0,s1,Movie,Dick Johnson Is Dead,Kirsten Johnson,NaN,United States,"September 25, 2021",2020,PG-13,90 min,Documentaries,"As her father nears the end of his life, filmm..."
1,1,s2,TV Show,Blood & Water,NaN,"Ama Qamata, Khosi Ngema, Gail Mabalane, Thaban...",South Africa,"September 24, 2021",2021,TV-MA,2 Seasons,"International TV Shows, TV Dramas, TV Mysteries","After crossing paths at a party, a Cape Town t..."
2,2,s3,TV Show,Ganglands,Julien Leclercq,"Sami Bouajila, Tracy Gotoas, Samuel Jouy, Nabi...",NaN,"September 24, 2021",2021,TV-MA,1 Season,"Crime TV Shows, International TV Shows, TV Act...",To protect his family from a powerful drug lor...
3,3,s4,TV Show,Jailbirds New Orleans,NaN,NaN,NaN,"September 24, 2021",2021,TV-MA,1 Season,"Docuseries, Reality TV","Feuds, flirtations and toilet talk go down amo..."
4,4,s5,TV Show,Kota Factory,NaN,"Mayur More, Jitendra Kumar, Ranjan Raj, Alam K...",India,"September 24, 2021",2021,TV-MA,2 Seasons,"International TV Shows, Romantic TV Shows, TV ...",In a city of coaching centers known to train I...
...,...,...,...,...,...,...,...,...,...,...,...,...,...
8802,8802,s8803,Movie,Zodiac,David Fincher,"Mark Ruffalo, Jake Gyllenhaal, Robert Downey J...",United States,"November 20, 2019",2007,R,158 min,"Cult Movies, Dramas, Thrillers","A political cartoonist, a crime reporter and a..."
8803,8803,s8804,TV Show,Zombie Dumb,NaN,NaN,NaN,"July 1, 2019",2018,TV-Y7,2 Seasons,"Kids' TV, Korean TV Shows, TV Comedies","While living alone in a spooky town, a young g..."
8804,8804,s8805,Movie,Zombieland,Ruben Fleischer,"Jesse Eisenberg, Woody Harrelson, Emma Stone, ...",United States,"November 1, 2019",2009,R,88 min,"Comedies, Horror Movies",Looking to survive in a world taken over by zo...
8805,8805,s8806,Movie,Zoom,Peter Hewitt,"Tim Allen, Courteney Cox, Chevy Chase, Kate Ma...",United States,"January 11, 2020",2006,PG,88 min,"Children & Family Movies, Comedies","Dragged from civilian life, a former superhero..."
8806,8806,s8807,Movie,Zubaan,Mozez Singh,"Vicky Kaushal, Sarah-Jane Dias, Raaghav Chanan...",India,"March 2, 2019",2015,TV-14,111 min,"Dramas, International Movies, Music & Musicals",A scrappy but poor boy worms his way into a ty...

### Sort index

In [77]:
df.set_index('show_id').sort_index()

,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
show_id,,,,,,,,,,,
s1,Movie,Dick Johnson Is Dead,Kirsten Johnson,NaN,United States,"September 25, 2021",2020,PG-13,90 min,Documentaries,"As her father nears the end of his life, filmm..."
s10,Movie,The Starling,Theodore Melfi,"Melissa McCarthy, Chris O'Dowd, Kevin Kline, T...",United States,"September 24, 2021",2021,PG-13,104 min,"Comedies, Dramas",A woman adjusting to life after a loss contend...
s100,TV Show,On the Verge,NaN,"Julie Delpy, Elisabeth Shue, Sarah Jones, Alex...","France, United States","September 7, 2021",2021,TV-MA,1 Season,"TV Comedies, TV Dramas","Four women — a chef, a single mom, an heiress ..."
s1000,Movie,Stowaway,Joe Penna,"Anna Kendrick, Toni Collette, Daniel Dae Kim, ...","Germany, United States","April 22, 2021",2021,TV-MA,116 min,"Dramas, International Movies, Thrillers",A three-person crew on a mission to Mars faces...
s1001,Movie,Wild Dog,Ahishor Solomon,"Nagarjuna Akkineni, Dia Mirza, Saiyami Kher, A...",NaN,"April 22, 2021",2020,TV-MA,126 min,"Action & Adventure, International Movies",A brash but brilliant Indian intelligence agen...
...,...,...,...,...,...,...,...,...,...,...,...
s995,Movie,This Lady Called Life,Kayode Kasum,"Bisola Aiyeola, Efa Iwara, Molawa Onajobi, Tin...",Nigeria,"April 23, 2021",2020,TV-14,120 min,"Dramas, International Movies, Romantic Movies","Abandoned by her family, young single mother A..."
s996,Movie,Vizontele,"Yılmaz Erdoğan, Ömer Faruk Sorak","Yılmaz Erdoğan, Demet Akbağ, Altan Erkekli, Ce...",Turkey,"April 23, 2021",2001,TV-MA,106 min,"Comedies, Dramas, International Movies","In 1974, a rural town in Anatolia gets its fir..."
s997,Movie,HOMUNCULUS,Takashi Shimizu,"Go Ayano, Ryo Narita, Yukino Kishii, Anna Ishi...",Japan,"April 22, 2021",2021,TV-MA,116 min,"Horror Movies, International Movies, Thrillers",Truth and illusion blurs when a homeless amnes...
s998,TV Show,Life in Color with David Attenborough,NaN,David Attenborough,"Australia, United Kingdom","April 22, 2021",2021,TV-PG,1 Season,"British TV Shows, Docuseries, International TV...","Using innovative technology, this docuseries e..."
s999,Movie,Searching For Sheela,NaN,Ma Anand Sheela,India,"April 22, 2021",2021,TV-14,58 min,"Documentaries, International Movies",Journalists and fans await Ma Anand Sheela as ...

### Explode cast column

In [78]:
df.assign(cast=df['cast'].str.split(',')).explode('cast')

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
0,s1,Movie,Dick Johnson Is Dead,Kirsten Johnson,NaN,United States,"September 25, 2021",2020,PG-13,90 min,Documentaries,"As her father nears the end of his life, filmm..."
1,s2,TV Show,Blood & Water,NaN,Ama Qamata,South Africa,"September 24, 2021",2021,TV-MA,2 Seasons,"International TV Shows, TV Dramas, TV Mysteries","After crossing paths at a party, a Cape Town t..."
1,s2,TV Show,Blood & Water,NaN,Khosi Ngema,South Africa,"September 24, 2021",2021,TV-MA,2 Seasons,"International TV Shows, TV Dramas, TV Mysteries","After crossing paths at a party, a Cape Town t..."
1,s2,TV Show,Blood & Water,NaN,Gail Mabalane,South Africa,"September 24, 2021",2021,TV-MA,2 Seasons,"International TV Shows, TV Dramas, TV Mysteries","After crossing paths at a party, a Cape Town t..."
1,s2,TV Show,Blood & Water,NaN,Thabang Molaba,South Africa,"September 24, 2021",2021,TV-MA,2 Seasons,"International TV Shows, TV Dramas, TV Mysteries","After crossing paths at a party, a Cape Town t..."
...,...,...,...,...,...,...,...,...,...,...,...,...
8806,s8807,Movie,Zubaan,Mozez Singh,Manish Chaudhary,India,"March 2, 2019",2015,TV-14,111 min,"Dramas, International Movies, Music & Musicals",A scrappy but poor boy worms his way into a ty...
8806,s8807,Movie,Zubaan,Mozez Singh,Meghna Malik,India,"March 2, 2019",2015,TV-14,111 min,"Dramas, International Movies, Music & Musicals",A scrappy but poor boy worms his way into a ty...
8806,s8807,Movie,Zubaan,Mozez Singh,Malkeet Rauni,India,"March 2, 2019",2015,TV-14,111 min,"Dramas, International Movies, Music & Musicals",A scrappy but poor boy worms his way into a ty...
8806,s8807,Movie,Zubaan,Mozez Singh,Anita Shabdish,India,"March 2, 2019",2015,TV-14,111 min,"Dramas, International Movies, Music & Musicals",A scrappy but poor boy worms his way into a ty...
8806,s8807,Movie,Zubaan,Mozez Singh,Chittaranjan Tripathy,India,"March 2, 2019",2015,TV-14,111 min,"Dramas, International Movies, Music & Musicals",A scrappy but poor boy worms his way into a ty...

### Explode listed_in column

In [79]:
df.assign(listed_in=df['listed_in'].str.split(',')).explode('listed_in')

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
0,s1,Movie,Dick Johnson Is Dead,Kirsten Johnson,NaN,United States,"September 25, 2021",2020,PG-13,90 min,Documentaries,"As her father nears the end of his life, filmm..."
1,s2,TV Show,Blood & Water,NaN,"Ama Qamata, Khosi Ngema, Gail Mabalane, Thaban...",South Africa,"September 24, 2021",2021,TV-MA,2 Seasons,International TV Shows,"After crossing paths at a party, a Cape Town t..."
1,s2,TV Show,Blood & Water,NaN,"Ama Qamata, Khosi Ngema, Gail Mabalane, Thaban...",South Africa,"September 24, 2021",2021,TV-MA,2 Seasons,TV Dramas,"After crossing paths at a party, a Cape Town t..."
1,s2,TV Show,Blood & Water,NaN,"Ama Qamata, Khosi Ngema, Gail Mabalane, Thaban...",South Africa,"September 24, 2021",2021,TV-MA,2 Seasons,TV Mysteries,"After crossing paths at a party, a Cape Town t..."
2,s3,TV Show,Ganglands,Julien Leclercq,"Sami Bouajila, Tracy Gotoas, Samuel Jouy, Nabi...",NaN,"September 24, 2021",2021,TV-MA,1 Season,Crime TV Shows,To protect his family from a powerful drug lor...
...,...,...,...,...,...,...,...,...,...,...,...,...
8805,s8806,Movie,Zoom,Peter Hewitt,"Tim Allen, Courteney Cox, Chevy Chase, Kate Ma...",United States,"January 11, 2020",2006,PG,88 min,Children & Family Movies,"Dragged from civilian life, a former superhero..."
8805,s8806,Movie,Zoom,Peter Hewitt,"Tim Allen, Courteney Cox, Chevy Chase, Kate Ma...",United States,"January 11, 2020",2006,PG,88 min,Comedies,"Dragged from civilian life, a former superhero..."
8806,s8807,Movie,Zubaan,Mozez Singh,"Vicky Kaushal, Sarah-Jane Dias, Raaghav Chanan...",India,"March 2, 2019",2015,TV-14,111 min,Dramas,A scrappy but poor boy worms his way into a ty...
8806,s8807,Movie,Zubaan,Mozez Singh,"Vicky Kaushal, Sarah-Jane Dias, Raaghav Chanan...",India,"March 2, 2019",2015,TV-14,111 min,International Movies,A scrappy but poor boy worms his way into a ty...
8806,s8807,Movie,Zubaan,Mozez Singh,"Vicky Kaushal, Sarah-Jane Dias, Raaghav Chanan...",India,"March 2, 2019",2015,TV-14,111 min,Music & Musicals,A scrappy but poor boy worms his way into a ty...

## 2.	Read DataFrame to create a pivot table.

### Pivot release year by type

In [80]:
df.pivot_table(values='release_year', index='type')

         release_year
type
Movie     2013.121514
TV Show   2016.605755

### Stack rating and duration

In [81]:
df[['rating','duration']].stack()

0     rating          PG-13
      duration       90 min
1     rating          TV-MA
      duration    2 Seasons
2     rating          TV-MA
                    ...
8804  duration       88 min
8805  rating             PG
      duration       88 min
8806  rating          TV-14
      duration      111 min
Length: 17614, dtype: str

### Reshape title column

In [82]:
df[['title']].values.reshape(-1,1)

array([['Dick Johnson Is Dead'],
       ['Blood & Water'],
       ['Ganglands'],
       ...,
       ['Zombieland'],
       ['Zoom'],
       ['Zubaan']], shape=(8807, 1), dtype=object)

### Convert wide to long format

In [83]:
pd.melt(df,
id_vars=['show_id','title'])

,show_id,title,variable,value
0,s1,Dick Johnson Is Dead,type,Movie
1,s2,Blood & Water,type,TV Show
2,s3,Ganglands,type,TV Show
3,s4,Jailbirds New Orleans,type,TV Show
4,s5,Kota Factory,type,TV Show
...,...,...,...,...
88065,s8803,Zodiac,description,"A political cartoonist, a crime reporter and a..."
88066,s8804,Zombie Dumb,description,"While living alone in a spooky town, a young g..."
88067,s8805,Zombieland,description,Looking to survive in a world taken over by zo...
88068,s8806,Zoom,description,"Dragged from civilian life, a former superhero..."
88069,s8807,Zubaan,description,A scrappy but poor boy worms his way into a ty...

### Pivot table by country

In [84]:
df.pivot_table(values='release_year', index='country')

                                                    release_year
country
, France, Algeria                                    2014.000000
, South Korea                                        2021.000000
Argentina                                            2016.000000
Argentina, Brazil, France, Poland, Germany, Den...   2017.000000
Argentina, Chile                                     2011.500000
...                                                          ...
Venezuela                                            2017.000000
Venezuela, Colombia                                  2007.000000
Vietnam                                              2017.714286
West Germany                                         1977.000000
Zimbabwe                                             2017.000000

[748 rows x 1 columns]

### 1. Count number of Movies and TV Shows by type

In [85]:
pd.pivot_table(
    df,
    values='show_id',
    index='type',
    aggfunc='count'
)

         show_id
type
Movie       6131
TV Show     2676

### 2. Count shows by rating and type

In [86]:
pd.pivot_table(
    df,
    values='show_id',
    index='type',
    columns='rating',
    aggfunc='count'
)

rating,66 min,74 min,84 min,G,NC-17,NR,PG,PG-13,R,TV-14,TV-G,TV-MA,TV-PG,TV-Y,TV-Y7,TV-Y7-FV,UR
type,,,,,,,,,,,,,,,,,
Movie,1.0,1.0,1.0,41.0,3.0,75.0,287.0,490.0,797.0,1427.0,126.0,2062.0,540.0,131.0,139.0,5.0,3.0
TV Show,NaN,NaN,NaN,NaN,NaN,5.0,NaN,NaN,2.0,733.0,94.0,1145.0,323.0,176.0,195.0,1.0,NaN

### Count shows released each year by type

In [87]:
pd.pivot_table(
    df,
    values='show_id',
    index='release_year',
    columns='type',
    aggfunc='count'
)

type          Movie  TV Show
release_year
1925            NaN      1.0
1942            2.0      NaN
1943            3.0      NaN
1944            3.0      NaN
1945            3.0      1.0
...             ...      ...
2017          767.0    265.0
2018          767.0    380.0
2019          633.0    397.0
2020          517.0    436.0
2021          277.0    315.0

[74 rows x 2 columns]

### 4. Count shows by country

In [88]:
pd.pivot_table(
    df,
    values='show_id',
    index='country',
    aggfunc='count'
)

                                                    show_id
country
, France, Algeria                                         1
, South Korea                                             1
Argentina                                                56
Argentina, Brazil, France, Poland, Germany, Den...        1
Argentina, Chile                                          2
...                                                     ...
Venezuela                                                 1
Venezuela, Colombia                                       1
Vietnam                                                   7
West Germany                                              1
Zimbabwe                                                  1

[748 rows x 1 columns]

### Count shows by genre

In [89]:
pd.pivot_table(
    df,
    values='show_id',
    index='listed_in',
    aggfunc='count'
)

                                                    show_id
listed_in
Action & Adventure                                      128
Action & Adventure, Anime Features                        1
Action & Adventure, Anime Features, Children & ...        4
Action & Adventure, Anime Features, Classic Movies        2
Action & Adventure, Anime Features, Horror Movies         1
...                                                     ...
TV Horror, TV Mysteries, Teen TV Shows                    1
TV Horror, Teen TV Shows                                  2
TV Sci-Fi & Fantasy, TV Thrillers                         1
TV Shows                                                 16
Thrillers                                                65

[514 rows x 1 columns]

### 6. Average release year by type

In [90]:
pd.pivot_table(
    df,
    values='release_year',
    index='type',
    aggfunc='mean'
)

         release_year
type
Movie     2013.121514
TV Show   2016.605755

### 7. Count shows added each year

In [91]:
pd.pivot_table(
    df,
    values='show_id',
    index='date_added',
    aggfunc='count'
)

                   show_id
date_added
 April 15, 2018          1
 April 16, 2019          1
 April 17, 2016          1
 April 20, 2017          1
 April 4, 2017           1
...                    ...
September 9, 2016        1
September 9, 2018        1
September 9, 2019        1
September 9, 2020        6
September 9, 2021        4

[1767 rows x 1 columns]

### 8. Count shows by rating

In [92]:
pd.pivot_table(
    df,
    values='show_id',
    index='rating',
    aggfunc='count'
)

          show_id
rating
66 min          1
74 min          1
84 min          1
G              41
NC-17           3
NR             80
PG            287
PG-13         490
R             799
TV-14        2160
TV-G          220
TV-MA        3207
TV-PG         863
TV-Y          307
TV-Y7         334
TV-Y7-FV        6
UR              3

### 9. Count shows by country and type

In [93]:
pd.pivot_table(
    df,
    values='show_id',
    index='country',
    columns='type',
    aggfunc='count'
)

type                                                Movie  TV Show
country
, France, Algeria                                     1.0      NaN
, South Korea                                         NaN      1.0
Argentina                                            38.0     18.0
Argentina, Brazil, France, Poland, Germany, Den...    1.0      NaN
Argentina, Chile                                      2.0      NaN
...                                                   ...      ...
Venezuela                                             1.0      NaN
Venezuela, Colombia                                   1.0      NaN
Vietnam                                               7.0      NaN
West Germany                                          1.0      NaN
Zimbabwe                                              1.0      NaN

[748 rows x 2 columns]

### 10. Count shows by year and rating

In [94]:
pd.pivot_table(
    df,
    values='show_id',
    index='release_year',
    columns='rating',
    aggfunc='count'
)

rating,66 min,74 min,84 min,G,NC-17,NR,PG,PG-13,R,TV-14,TV-G,TV-MA,TV-PG,TV-Y,TV-Y7,TV-Y7-FV,UR
release_year,,,,,,,,,,,,,,,,,
1925,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1942,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1943,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3.0,NaN,NaN,NaN,NaN
1944,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.0,NaN,NaN,1.0,NaN,NaN,NaN,NaN
1945,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.0,NaN,2.0,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2017,NaN,1.0,NaN,1.0,NaN,2.0,15.0,32.0,73.0,251.0,26.0,451.0,111.0,31.0,37.0,NaN,NaN
2018,NaN,NaN,NaN,2.0,1.0,1.0,31.0,30.0,52.0,268.0,26.0,549.0,105.0,41.0,40.0,1.0,NaN
2019,NaN,NaN,NaN,1.0,NaN,NaN,12.0,19.0,39.0,252.0,23.0,500.0,98.0,50.0,36.0,NaN,NaN
2020,NaN,NaN,NaN,1.0,NaN,NaN,15.0,21.0,48.0,174.0,45.0,469.0,80.0,59.0,41.0,NaN,NaN
2021,NaN,NaN,NaN,NaN,NaN,NaN,11.0,14.0,21.0,151.0,21.0,270.0,45.0,26.0,33.0,NaN,NaN

## 3.	Read DataFrame to create a cross table.

### Count Movies and TV Shows by type and rating

In [95]:
pd.crosstab(df['type'], df['rating'])

rating,66 min,74 min,84 min,G,NC-17,NR,PG,PG-13,R,TV-14,TV-G,TV-MA,TV-PG,TV-Y,TV-Y7,TV-Y7-FV,UR
type,,,,,,,,,,,,,,,,,
Movie,1,1,1,41,3,75,287,490,797,1427,126,2062,540,131,139,5,3
TV Show,0,0,0,0,0,5,0,0,2,733,94,1145,323,176,195,1,0

### Count shows by country and type

In [96]:
pd.crosstab(df['country'], df['type'])

type                                                Movie  TV Show
country
, France, Algeria                                       1        0
, South Korea                                           0        1
Argentina                                              38       18
Argentina, Brazil, France, Poland, Germany, Den...      1        0
Argentina, Chile                                        2        0
...                                                   ...      ...
Venezuela                                               1        0
Venezuela, Colombia                                     1        0
Vietnam                                                 7        0
West Germany                                            1        0
Zimbabwe                                                1        0

[748 rows x 2 columns]

### 3. Count shows by release year and type

In [97]:
pd.crosstab(df['release_year'], df['type'])

type          Movie  TV Show
release_year
1925              0        1
1942              2        0
1943              3        0
1944              3        0
1945              3        1
...             ...      ...
2017            767      265
2018            767      380
2019            633      397
2020            517      436
2021            277      315

[74 rows x 2 columns]

### Count shows by rating and type

In [99]:
pd.crosstab(df['rating'], df['type'])

type      Movie  TV Show
rating
66 min        1        0
74 min        1        0
84 min        1        0
G            41        0
NC-17         3        0
NR           75        5
PG          287        0
PG-13       490        0
R           797        2
TV-14      1427      733
TV-G        126       94
TV-MA      2062     1145
TV-PG       540      323
TV-Y        131      176
TV-Y7       139      195
TV-Y7-FV      5        1
UR            3        0

### Count shows by country and rating

In [100]:
pd.crosstab(df['country'], df['rating'])

rating,66 min,74 min,84 min,G,NC-17,NR,PG,PG-13,R,TV-14,TV-G,TV-MA,TV-PG,TV-Y,TV-Y7,TV-Y7-FV,UR
country,,,,,,,,,,,,,,,,,
", France, Algeria",0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0
", South Korea",0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0
Argentina,0,0,0,0,0,2,0,0,1,7,2,39,3,2,0,0,0
"Argentina, Brazil, France, Poland, Germany, Denmark",0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0
"Argentina, Chile",0,0,0,0,0,0,0,0,0,1,0,1,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Venezuela,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0
"Venezuela, Colombia",0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0
Vietnam,0,0,0,0,0,0,0,0,0,3,1,3,0,0,0,0,0
West Germany,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0
Zimbabwe,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0

### 6. Count shows by genre and type

In [101]:
pd.crosstab(df['listed_in'], df['type'])

type                                                Movie  TV Show
listed_in
Action & Adventure                                    128        0
Action & Adventure, Anime Features                      1        0
Action & Adventure, Anime Features, Children & ...      4        0
Action & Adventure, Anime Features, Classic Movies      2        0
Action & Adventure, Anime Features, Horror Movies       1        0
...                                                   ...      ...
TV Horror, TV Mysteries, Teen TV Shows                  0        1
TV Horror, Teen TV Shows                                0        2
TV Sci-Fi & Fantasy, TV Thrillers                       0        1
TV Shows                                                0       16
Thrillers                                              65        0

[514 rows x 2 columns]

### 7. Count shows by director and type

In [102]:
pd.crosstab(df['director'], df['type'])

type                 Movie  TV Show
director
A. L. Vijay              2        0
A. Raajdheep             1        0
A. Salaam                1        0
A.R. Murugadoss          2        0
Aadish Keluskar          1        0
...                    ...      ...
Çagan Irmak              1        0
Ísold Uggadóttir         1        0
Óskar Thór Axelsson      1        0
Ömer Faruk Sorak         2        0
Şenol Sönmez             2        0

[4528 rows x 2 columns]

###  Count shows by type and duration

In [103]:
pd.crosstab(df['type'], df['duration'])

duration,1 Season,10 Seasons,10 min,100 min,101 min,102 min,103 min,104 min,105 min,106 min,...,90 min,91 min,92 min,93 min,94 min,95 min,96 min,97 min,98 min,99 min
type,,,,,,,,,,,,,,,,,,,,,
Movie,0,0,1,108,116,122,114,104,101,111,...,152,144,129,146,146,137,130,146,120,118
TV Show,1793,7,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

### 9. Count shows by release year and rating

In [104]:
pd.crosstab(df['release_year'], df['rating'])

rating,66 min,74 min,84 min,G,NC-17,NR,PG,PG-13,R,TV-14,TV-G,TV-MA,TV-PG,TV-Y,TV-Y7,TV-Y7-FV,UR
release_year,,,,,,,,,,,,,,,,,
1925,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0
1942,0,0,0,0,0,0,0,0,0,2,0,0,0,0,0,0,0
1943,0,0,0,0,0,0,0,0,0,0,0,0,3,0,0,0,0
1944,0,0,0,0,0,0,0,0,0,2,0,0,1,0,0,0,0
1945,0,0,0,0,0,0,0,0,0,2,0,2,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2017,0,1,0,1,0,2,15,32,73,251,26,451,111,31,37,0,0
2018,0,0,0,2,1,1,31,30,52,268,26,549,105,41,40,1,0
2019,0,0,0,1,0,0,12,19,39,252,23,500,98,50,36,0,0
2020,0,0,0,1,0,0,15,21,48,174,45,469,80,59,41,0,0
2021,0,0,0,0,0,0,11,14,21,151,21,270,45,26,33,0,0

### 10. Count shows by country and genre

In [105]:
pd.crosstab(df['country'], df['listed_in'])

listed_in,Action & Adventure,"Action & Adventure, Anime Features, Children & Family Movies","Action & Adventure, Anime Features, Classic Movies","Action & Adventure, Anime Features, Horror Movies","Action & Adventure, Anime Features, International Movies","Action & Adventure, Anime Features, Sci-Fi & Fantasy","Action & Adventure, Children & Family Movies","Action & Adventure, Children & Family Movies, Classic Movies","Action & Adventure, Children & Family Movies, Comedies","Action & Adventure, Children & Family Movies, Cult Movies",...,"TV Dramas, TV Sci-Fi & Fantasy, Teen TV Shows","TV Dramas, TV Thrillers","TV Dramas, Teen TV Shows","TV Horror, TV Mysteries, TV Sci-Fi & Fantasy","TV Horror, TV Mysteries, TV Thrillers","TV Horror, TV Mysteries, Teen TV Shows","TV Horror, Teen TV Shows","TV Sci-Fi & Fantasy, TV Thrillers",TV Shows,Thrillers
country,,,,,,,,,,,,,,,,,,,,,
", France, Algeria",0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
", South Korea",0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
Argentina,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
"Argentina, Brazil, France, Poland, Germany, Denmark",0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
"Argentina, Chile",0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Venezuela,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
"Venezuela, Colombia",0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
Vietnam,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
West Germany,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
Zimbabwe,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

### Crosstab with percentage

In [106]:
pd.crosstab(df['type'], df['rating'], normalize='index')

rating,66 min,74 min,84 min,G,NC-17,NR,PG,PG-13,R,TV-14,TV-G,TV-MA,TV-PG,TV-Y,TV-Y7,TV-Y7-FV,UR
type,,,,,,,,,,,,,,,,,
Movie,0.000163,0.000163,0.000163,0.00669,0.000489,0.012237,0.046827,0.079948,0.130038,0.232828,0.020558,0.336433,0.088106,0.021374,0.022679,0.000816,0.000489
TV Show,0.000000,0.000000,0.000000,0.00000,0.000000,0.001870,0.000000,0.000000,0.000748,0.274121,0.035153,0.428197,0.120793,0.065819,0.072924,0.000374,0.000000